[profile.default]
optimizer_runs = 1000000
remappings = [
  "@clones/=lib/clones-with-immutable-args/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/royalty-registry-solidity/lib/openzeppelin-contracts-upgradeable/contracts/",
  "lssvm2/=lib/lssvm2/src/",
  "manifoldxyz/=lib/royalty-registry-solidity/contracts/",
]
verbosity = 1
via_ir = true
solc_version = "0.8.20"

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
goerli = {key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api"}
mainnet = {key = "${ETHERSCAN_KEY}"}
